server:
  port: 10012

eureka:
  instance:
#    hostname: localhost
    hostname: eureka-10012
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://eureka-10010:10010/eureka,http://eureka-10011:10011/eureka

